#! /usr/bin/env bash

# Generate 3 random lowercase words (6 letters each)
word1=$(tr -dc 'a-z' </dev/urandom | head -c6)
word2=$(tr -dc 'a-z' </dev/urandom | head -c6)
word3=$(tr -dc 'a-z' </dev/urandom | head -c6)
word4=$(tr -dc 'a-z' </dev/urandom | head -c6)


# Export variables for use in find -exec
export word1 word2 word3 word4

# Rename directories (updated for com.anatdx.yukisu)
# Exclude murasaki-api which is a submodule library
find app -depth -type d -name 'com' -execdir mv {} "$word1" \;
find app -depth -type d -name 'anatdx' -execdir mv {} "$word2" \;
find app -depth -type d -name 'yukisu' -execdir mv {} "$word3" \;
find app -depth -type d -name 'io' -execdir mv {} "$word4" \;


# Replace inside files (updated for com.anatdx.yukisu)
# Also restrict to app directory to avoid touching submodules
find app -type f -exec sed -i \
    -e "s/com\.anatdx\.yukisu/$word1.$word2.$word3/g" \
    -e "s/io\.anatdx\.yukisu/$word4.$word2.$word3/g" \
    -e "s/com\/anatdx\/yukisu/$word1\/$word2\/$word3/g" \
    -e "s/io\/anatdx\/yukisu/$word4\/$word2\/$word3/g" \
    -e "s/io_anatdx_yukisu/${word4}_${word2}_${word3}/g" \
    -e "s/com_anatdx_yukisu/${word1}_${word2}_${word3}/g" {} +

# add -spoofed on tags
sed -i -e '/fun getGitDescribe(): String {/,/^    }/ s/\.trim()$/.trim() + "-spoofed"/' build.gradle.kts
