#include "assets.hpp"
#include "../defs.hpp"
#include "../log.hpp"
#include "../utils.hpp"
#include <filesystem>
#include <string>

namespace fs = std::filesystem;

namespace ksud {

// Note: ensure_binaries() is implemented in generated/assets_data.cpp
// Generated by scripts/embed_assets.py at build time

}  // namespace ksud
